# Site settings
title: Mu script
description: Home of the Mu scripting language
footnote: Hi! I'm glad you read this far.

url: "http://mu-script.org"
github: "https://github.com/mu-script/mu"

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
